### ISSUE TITLE
ball falling through floor

### ISSUE THREAD

**Issue by darkjoy2k2** [Microsoft/Windows-appsample-marble-maze#2]
I imported the code to monogame and put the highscores and controls to windows platform. I did not manipulate any game physics or calculations.

The ball always falls through the floor except for the bridge area, which responds perfectly. Walls and pits respond fine. Contentimporter works well and all .tags are imported properly from mesh. Any ideas? Are there math differences between xna and monogame? Or handling of calculations between windowsPhone/Windows?

**Comment by abbycar** [comment]
Hi!

I'm not seeing this problem when run in Visual Studio 2017, so it most likely has something to do with a porting issue to MonoGame. Without looking at your code, a possible issue could be a difference in the end values regarding the positioning/collision detection between the ball and normal floor. This may be because of a difference in how the game window size/positioning is calculated in MonoGame. 

Your best bet on finding a solution is seeking some help from the [MonoGame community](http://community.monogame.net/). :)

Thanks for reaching out and testing out the sample!
